CREATE TABLE IF NOT EXISTS author
(
  AUTHOR_ID INTEGER PRIMARY KEY NOT NULL,
  FIRST_NAME VARCHAR(50) NOT NULL,
  LAST_NAME VARCHAR(50) NOT NULL,
  SEX VARCHAR(10),
  BIRTH_DATE DATE,
);

CREATE TABLE IF NOT EXISTS reward
(
  REWARD_ID INTEGER PRIMARY KEY NOT NULL,
  YEAR INTEGER NOT NULL,
  TITLE VARCHAR(200),
  AUTOR_ID BIGINT REFERENCES author (AUTHOR_ID)
);

CREATE TABLE IF NOT EXISTS book
(
  BOOK_ID INTEGER PRIMARY KEY NOT NULL,
  TITLE VARCHAR(255) NOT NULL,
  ISBN VARCHAR(13) NOT NULL,
  GENRE VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS author_book (
  AUTHOR_ID BIGINT REFERENCES author (AUTHOR_ID),
  BOOK_ID BIGINT REFERENCES book (BOOK_ID)
);



